# -*- coding: utf-8 -*-
"""jupyter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qoxi26B7ss6JhA29Pii84-IX9cVy3ECR
"""

import pygame
pygame.init()
screen = pygame.display.set_mode((1024, 720))
clock = pygame.time.Clock()
running = True

#Player
player = pygame.image.load('/Users/luskousko/Desktop/Work/pics_pygame/cat.png').convert_alpha()
player = pygame.transform.scale(player,(100,100))
flipping_player = player


#Weapons
lightsaber = pygame.image.load('/Users/luskousko/Desktop/Work/pics_pygame/lightsaber.png').convert_alpha()
lightsaber =    pygame.transform.scale(lightsaber,(80,80))
lightsaber = pygame.transform.rotate(lightsaber,225)


#Second weapon or more weapons
gun = pygame.image.load('/Users/luskousko/Desktop/Work/pics_pygame/gun.png').convert_alpha()
gun = pygame.transform.scale(gun, (80, 80))

#Inventory ------------------------
#ZOZNAM
weapons = [{
        "name": "lightsaber",
        "image": lightsaber,
        "base_rotation": 0,
        "rotates": True,
        "offset": (10, 10)},

        {"name": "gun",
        "image": gun,
        "base_rotation": 0,
        "rotates": False,
         "offset": (60, 40)}]
current_weapon_index = 0

#Variables
player_x = 0
player_y = 0
angle = 0
tocenie_meca = False
rychlost = 8
pohyb_hore = False
pohyb_dole = False
pohyb_doprava = False
pohyb_dolava = False





def switch_weapon():
    global current_weapon_index, angle
    current_weapon_index = (current_weapon_index + 1) % len(weapons)
    angle = 0  #reset to angle 0 when switching

def set_weapon(index):
    global current_weapon_index, angle
    if 0 <= index < len(weapons):
        current_weapon_index = index
        angle = 0



def spracuj_keydown(event):
    global pohyb_hore, pohyb_dole, pohyb_doprava, pohyb_dolava, tocenie_meca
    if event.key == pygame.K_w:
        pohyb_hore = True
    if event.key == pygame.K_s:
        pohyb_dole = True
    if event.key == pygame.K_a:
        pohyb_dolava = True
    if event.key == pygame.K_d:
        pohyb_doprava = True
    if event.key == pygame.K_SPACE:
        tocenie_meca = True

    #------------------------------------------------------------------
    if event.key == pygame.K_e:
        switch_weapon()
    if event.key == pygame.K_1:
        set_weapon(0)
    if event.key == pygame.K_2:
        set_weapon(1)


def spracuj_keyup(event):
    global pohyb_hore, pohyb_dole, pohyb_doprava, pohyb_dolava,  tocenie_meca
    if event.key == pygame.K_w:
        pohyb_hore = False
    if event.key == pygame.K_s:
        pohyb_dole = False
    if event.key == pygame.K_a:
        pohyb_dolava = False
    if event.key == pygame.K_d:
        pohyb_doprava = False
    if event.key == pygame.K_SPACE:
        tocenie_meca = False


def pohyb_hraca():
    global player_x, player_y, angle, player
    if pohyb_hore:
        player_y -= rychlost
    if pohyb_dole:
        player_y += rychlost
    if pohyb_dolava:
        player_x -= rychlost
        player = pygame.transform.flip(flipping_player, True, False)
    if pohyb_doprava:
        player_x += rychlost
        player = flipping_player



    aktualna_zbran = weapons[current_weapon_index]
    if tocenie_meca and aktualna_zbran["rotates"]:
        angle += 10

    #Border ------------------------------------------
    if player_x < 0:
        player_x = 0
    if player_y < 0:
        player_y = 0
    if player_x > 1024 - player.get_width():
        player_x = 1024 - player.get_width()
    if player_y > 720 - player.get_height():
        player_y = 720 - player.get_height()

#Main loop
while running:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False

        if event.type == pygame.KEYDOWN:
            spracuj_keydown(event)

        if event.type == pygame.KEYUP:
            spracuj_keyup(event)

    pohyb_hraca()
    screen.fill((255, 255, 255))
    screen.blit(player, (player_x, player_y))

    aktualna_zbran = weapons[current_weapon_index]
    weapon_image = aktualna_zbran["image"]
    rotated_weapon = pygame.transform.rotate(weapon_image,aktualna_zbran["base_rotation"] + angle)
    offset_x, offset_y = aktualna_zbran["offset"]
    screen.blit(rotated_weapon, (player_x + offset_x, player_y + offset_y))

    #rotated_sword = pygame.transform.rotate(lightsaber, angle)
    #screen.blit(rotated_sword, (player_x + 70, player_y + 25))
    pygame.display.update()
    clock.tick(60)

pygame.quit()

"""TODO:
FIXME: treba opravit
NOTE:"""